srun: error: ioctl(TIOCGWINSZ): Inappropriate ioctl for device
srun: error: Not using a pseudo-terminal, disregarding --pty option
Traceback (most recent call last):
  File "/data/vision/polina/users/clintonw/code/vision_final/scripts/train_classifier.py", line 203, in <module>
    main(vars(get_args()))
  File "/data/vision/polina/users/clintonw/code/vision_final/scripts/train_classifier.py", line 112, in main
    pred = par_model(imgs, context)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "../networks/base.py", line 66, in forward
    ux = self.film(ux)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/data/vision/polina/shared_software/anaconda3/envs/clinton/lib/python3.6/site-packages/torch/nn/functional.py", line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1024 x 832], m2: [4160 x 128] at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/generic/THCTensorMathBlas.cu:249
srun: error: cassia: task 0: Exited with exit code 1
